apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhtap-go-app-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/rhtap-go-app-3:a9af6c333561de93dd12a61ec8f1b1111f3758ec@sha256:84ed2c4ff4c8298bfac563c5377c746e4c036b17961c8f8979117681b0391335
          name: container-image
