apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-go-app-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-go-app-3 
  name: rhtap-go-app-3
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-go-app-3 
